## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
    - linux
    - osx
julia:
    - 0.6
    - nightly
notifications:
    email: false
#script: # use the default script setting which is the same as the following
#    - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#    - julia --check-bounds=yes -e 'Pkg.clone(pwd()); Pkg.build("SimJulia"); Pkg.test("SimJulia"; coverage=true)'
after_success:
    - julia -e 'cd(Pkg.dir("PFlow")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder()); Codecov.submit(Codecov.process_folder())'
    - julia -e 'Pkg.add("Documenter"); cd(Pkg.dir("SimJulia")); include(joinpath("docs", "make.jl"))'
